### ISSUE TITLE
Podcast episode status showing played progress

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-ios#104]
Once we add the publication date to the episode list in the media player, we need to add a progress bar that shows if and how much of an episode has been played. The "min left" is a handy way of showing this. Anything less than 2 minutes is rounded up to showing as played.

Our current list
![IMG_2473A60FF4B0-1](https://user-images.githubusercontent.com/814886/209978726-3286dae9-2027-4c9b-9414-5d13b1f08d3d.jpeg)

Apple's display with date and progress
![IMG_99F2375EDD3B-1](https://user-images.githubusercontent.com/814886/209978906-6f725ff3-b063-494b-b2d4-a24c7f011eb1.jpeg)

**Comment by tomastiminskas** [comment]
@pitoi sounds good, and I think we have a played progress bar design on the recommendations

<img width="499" alt="Screen Shot 2022-12-29 at 13 33 49" src="https://user-images.githubusercontent.com/2242281/209982353-602f21ba-61d0-4042-bf18-9705cd6bc0d5.png">

But maybe the best is to have Milan reviewing the podcast episodes list on podcast player. Actually the download button and downloading progress is something I built in the past without any designs so it doesn't look really well. Having a new design for the podcast episodes with title, description, publish date and played progress bar would be perfect. 

Just as a note, we would show the progress bar for those episodes that were played already. Since we need the duration of the episode and that is loaded and stored the first time it's played. 

@Antanasijevic

**Comment by jimBeaux27** [comment]
Closing this because it's being addressed in #145
