### ISSUE TITLE
Feed > Listen Now

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-ios#118]
The "Listen now" on the standard Apple Podcast player shows new episodes for the shows you subscribe to.
In ours it seems to show the last played even if they have been played to the end.

Let's change that section to show new episodes from the Following section and display the progress bar to show how much as been played.

**Comment by tomastiminskas** [comment]
I will do the changes to always show the last episode (stored on device db) for each podcast on Listen Now section, same for Watch Now section and Read Now. 

But as it's done right now, the episodes update is done when entering the player. So if a new episode is released on a show, it won't show up on Sphinx until you enter the player. That's because we have an endpoint that fetches one podcast at a time, and we perform that action at specific moments (when entering the player, when entering the tribe chat view of a podcast)

We could improve this by running the update endpoint call for each of the followed feeds one by one when entering the app. Or something like that

@pitoi ping me tomorrow when you are free and I can explain more in detail so we are on the same page and we can define the best approach for this

@Antanasijevic we would need designs to show the progress bar on the Listen Now section rows.

**Comment by Antanasijevic** [comment]
@pitoi Here is a possible solution in UI side. 
Original intention was, for "Listen Now" section to show latest episodes, and tap on each would start playing selected episode. "Following" section should show podcasts user is following, and tap on each would, ideally, open a page with general info about selected podcast and list of all episodes.

On "Listen Now" section we can add same progress bar we planned on other pages, indicating if episode is already playing, has been played and how much is left. Additionally, we can add a small label "New" next to source icon, that may be visible only on unplayed episodes. "New" label may be effective if we want to point out that these are new episodes. I would avoid adding more elements like date, since it item is already crowded. Also, in order to keep it as clear as possible, i think we should limit podcast title to one row, and episode name to two rows.

For "Following" sections, (once we make page with podcast info and full episode list) i suggest we show Podcast name (limited to one row) and podcast description (limited to two rows)

![image](https://user-images.githubusercontent.com/13258550/211038654-6a95ebd8-c500-4701-876e-01aca01d1c7e.png)

**Comment by tomastiminskas** [comment]
@pitoi on the same process that @jimBeaux27 built for pre downloading last episode of each podcast, we will be adding the logic to fetch new episodes for each podcast/video/newsletter and some logic to pre load the duration of last episodes. With that running in background we should improve UX a lot and be able to show updated content on Feed without needing to enter the player. We will also reduce the delay when entering player until it starts playing.

He is now working on it, so we might have something on Monday to test. I will take care of the progress bar addition as a separated task once the fetch logic is done.

**Comment by jimBeaux27** [comment]
#113 should be able to address this
