### ISSUE TITLE
Feed > Listen: Played audio not matching selection

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-ios#119]
When opening an episode list, I tapped on the first show (related to China), but the 5th episode plays:

![IMG_4F58BC66581A-1](https://user-images.githubusercontent.com/814886/211167650-271e7d48-028c-4e51-bfc1-21d0e19b2aac.jpeg)

I was going to test other shows, but now the app crashes before the lockscreen shows so I can't use the app anymore.

**Comment by jimBeaux27** [comment]
Thanks @pitoi . I tried this myself and could not get it to happen but I will keep trying. If you see a crash from this again can you please make note of it in the crash report so that I can tag it properly and analyze it in testflight?

@tomastiminskas there seems to be other issues with dequeuing and applying indices correctly on the cells so maybe this is related.

**Comment by tomastiminskas** [comment]
@pitoi @jimBeaux27 I will look into this today. Never experienced it and seems an old issue because we didn't do changes on the old podcast player. But good to fix it now

**Comment by tomastiminskas** [comment]
@pitoi this should be fixed in next release coming out later today
