### ISSUE TITLE
Feed: All tabs, subscriptions not restored after reinstall

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-ios#121]
Right now, subscriptions and episode play state are not restored when doing a clean install of the app. Need to verify they are being replicated on relay.

**Comment by tomastiminskas** [comment]
@pitoi there is no logic related with syncing subscriptions for podcasts/videos/newsletters to relay. So that is not implemented. We just discussed briefly with @jimBeaux27  and he will be planning and putting the details here, so then we can review and ask Kevin for the relay side changes. 

We will be basically tracking the podcast/videos/newsletter you are subscribed to, so then we can fetch content back during restore and feed will look exactly the same after account is restored

**Comment by jimBeaux27** [comment]
Thanks @tomastiminskas you basically confirmed my analysis that all the subscriptions are stored on the local device DB and we do not yet have a way to store them in the relay.

I think this is a great feature to work on and also it relates to #107 so it's going to make a difference on multiple fronts. I am drafting up the basic information we will need to be able to store and retrieve to make this vision a reality.

**Comment by tomastiminskas** [comment]
@jimBeaux27 Good to linked this ticket to #107 since it's definitely related. Once we have feed subscriptions tracked in relay, we can separate feature into 2 tasks:
- Restore all subscriptions on restore
- Restore subscriptions that you might have subscribed on other device on app launch

All this will apply to android as well

**Comment by jimBeaux27** [comment]
Agreed. This is a sphinx wide infrastructural update that we need to coordinate.

I drafted a preliminary spec that I'm sure could evolve but I think it has most of what we would need:

**Persisting Feeds Across Devices**
1. Need an endpoint that allows read/write of ContentFeedStatus
2. Most likely an array
3. Each element needs to have the following at a minimum
    1. Content Feed ID (string)
    2. Subscription status (bool)
    3. LastUsedItemInfo (Maybe custom object
        1. ContentItemID (string)
        2. ContentType (enum?)
        3. PlaybackDuration (Number)
        4. LastPlayedTime (Number)

Ex:
{
	feedItem1 : {
		feedID: 1234,
		subscription_status: true,
		last_used_item_info: {
			content_id: 1234,
			contentType: 1,
			playback_duration: 3600,
			playback_current_time : 1800
		}
	}

	feedItem2: {
		feedID: 5678,
		subscription_status: true,
		last_used_item_info: {
			content_id: 5678,
			contentType: 1,
			playback_duration: 3600,
			playback_current_time : 1800
		}
	}

}

**Comment by tomastiminskas** [comment]
@jimBeaux27 we definitely need to add: 
- FeedUrl (without the feed url we can't fetch feed content again after restoring account)
- ChatId (it is optional, but if the feed was subscribed by joining a tribe, we need the chatId reference)

We can start with some logic on the app until we have the relay side changes. 
- Build the restore logic to be append during the restore process. You can do it using an array of 3/4 items as the ones you described above (with the additions I mentioned)
- Build the save logic: the fetch query to get all feed on db, and the parsing logic to get the json array to be sent to really when the endpoint is ready.

**Comment by jimBeaux27** [comment]
🫡

**Comment by jimBeaux27** [comment]
Hi @tomastiminskas I went ahead and made some changes on this branch: https://github.com/stakwork/sphinx-ios/tree/jc/develop/sync-pod-statuses

Most notable changes are:
- Added a new model called ContentFeedStatus (see below)
- Added methods to the ActionsManager and API to save/get ContentFeedStatus objects

`
import Foundation
import ObjectMapper

class ContentFeedStatus: Mappable {
    var feedID: String?
    var subscriptionStatus:Bool?
    var lastItemInfo:ContentFeedLastItem?
    var feedURL: String?
    var chatID:String?
    
    
    required convenience init(map: Map) {
        self.init()
    }
    
    func mapping(map: Map) {
        feedID            <- map["feed_id"]
        subscriptionStatus            <- map["subscription_status"]
        let json = map.JSON
        if let valid_last_item = json["last_item_info"] as? ContentFeedLastItem{
            lastItemInfo         = valid_last_item
        }
        feedURL            <- map["feed_url"]
        chatID            <- map["chat_id"]
    }
}

`

**Comment by tomastiminskas** [comment]
Changes on models:
- Rename `contentID` to `itemID` (to be consistent with ContentFeed model)
- Remove `contentType` (not actually needed)
- Remove optionals for `feedID`, `feedURL` and `subscriptionStatus`
- Add `satsPerMinute` to sync configuration about sats per minute to be streamed to creator while playing (right now this only works for tribe podcasts but it would be good to add it on player so it can be customized also for content subscribed by search)
- Add `playerSpeed` to sync speed of the player per podcast

IMO we could make all the same model, since there will be always juts one LastItem played so it will be something like this:

```
class ContentFeedStatus {
    var feedID: String
    var feedURL: String?
    var subscriptionStatus:Bool
    var chatID:String?
    var itemID: String?
    var playbackDuration: Int?
    var lastPlayedTime: Int?
    var satsPerMinute: Int?
    var playerSpeed: Double?
}
```

@jimBeaux27 we need to think and plan where to call both endpoints and how to handle sync logic to prevent data loss. As user can unsubscribed to a podcast/video/newsletter (that he had subscribed before from search), we need to think the best way to sync that unsubscription as well. Also think about how to handle cases where user is using 2 client apps at the same time and performing changes on subscription on both (could be an edge case but good to think about them now). If you have ideas please put them in here so we are on the same page. 

My first thought is:
- GET feed status from relay on `appDidBecomeActve`
- POST feed status to relay on `appDidEnterBackground` (relay will just delete all existing records and insert those coming from the app, so if you unsubscribed from a podcast, then it won't be sent to relay and then relay will delete it)

NOTE on ChatMetaData
- Right now for tribe podcasts we are storing data on `chat.metaData` and using it to sync between devices. @jimBeaux27 check the app code regarding this so you get familiar with it. We are storing `episode-id`, `current-time`, `player-speed` and `sats-per-minute`, so I think this will become obsolete with the new table/logic

## RELAY CHANGES (@soup20 or @kevkevinpal)
We need a db on relay with the same columns and the 2 endpoints:
- GET to return all records on new table (content_feed_status)
- POST to insert records (should receive array of objects with same structure)

**Comment by jimBeaux27** [comment]
Thanks @tomastiminskas this is a good start. I think most of your suggestions are right on point.

I'll take a look at chat.metaData

Re this one:
- POST feed status to relay on appDidEnterBackground (relay will just delete all existing records and insert those coming from the app, so if you unsubscribed from a podcast, then it won't be sent to relay and then relay will delete it)

I actually think that a PUT request is more appropriate because it does exactly what you say: inserts a new entry or updates an old one. I took an example from the code base and adapted it for the save API request I wrote.

**Comment by jimBeaux27** [comment]
RE: When to do the GET request
Sounds good I will change things to conform to that

RE: When to do the POST request
I just incorporated it in the syncActionsInBackground since I figure they're related and that is appropriate. These both occur in appDidEnterBackground

**Comment by tomastiminskas** [comment]
@jimBeaux27 I was thinking about this while working on the Player refactor and I'm wondering if we should create the ContentFeedStatus model as a table on CoreDate so that information is stored directly in the model as it will be persisted in relay. 

Right now we are storing most of that information in NSUserDefaults and parsing it to a ContentFeedStatus model before sending it to relay when app go into background. But maybe having the model in CoreData is more clear and better in the long term, mostly considering I'm redoing the podcast player helper and it may be a good moment to get rid of all that data we are persisting in UserDefaults. 

Let me know what do you think
