### ISSUE TITLE
Text field not showing

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-ios#130]
I believe this happened when a push notification came in while I was in the Feed and a podcast was active. I believe I tapped on the notification popup and this text chat appeared.
It may explain why the area normally taken up by the player bar is hiding or preventing msg txt area from appearing.

![IMG_9269](https://user-images.githubusercontent.com/814886/215297902-bfc228cc-65d3-46d0-8923-dc0a991825ab.PNG)

**Comment by jimBeaux27** [comment]
I noticed a similar issue (see https://github.com/stakwork/sphinx-ios/issues/136). But upon further review I struggled to recreate both that and this.

One point of clarification: you had a *banner* notification and not a *push* notification that caused the issue correct? If it is the former then after about 10 tries I could not reproduce. But I will try a bit some more.

**Comment by jimBeaux27** [comment]
I have a beat on this @tomastiminskas I think what's happening is ChatAccessoryView is not loading due to an issue with either timing or the path to creation from deeplinks not being correct. I think ideally we might want to detect that we are in the feeds section and back out then go find the chatID from the chat rather than simply pushing the ChatVC straight from the NewPodcastPlayerVC
