### ISSUE TITLE
Update the Podcast List UI

### ISSUE THREAD

**Issue by jimBeaux27** [stakwork/sphinx-ios#145]
Based on this design: https://github.com/stakwork/sphinx/issues/245

**Comment by jimBeaux27** [comment]
Addressed in #147

**Comment by tomastiminskas** [comment]
Fixes needed:

### PODCAST
- Space between date label - dot - time left label is not correct (every place where there's a dot the space to both sides should be the same). Maybe you are setting fixed label width instead of making them adapt to text. 
- Vertical space between episode image - description label - line with icon/date/time left seems wrong. In the FIGMA designs it seems there is same space between image and description than between description and the line below it
- Space between time left and progress bar is too big
- Time left format is wrong. Seems to change depending if I test on simulator or my device. On my device it shows "13m left", but it should be "13 min left" (You can get the right format from the LISTEN NOW rows)
- If not played (current time = 0), then “left” word shouldn't be there, just show episode duration on label and progress bar should be hidden as well.
- Seems title font weight is not right (check all font sizes and weight). When playing it becomes blue and it looks thinner than on the designs
- The PLAYED icon on row is in a bad resolution (looks bad)
- Add semi transparent layer and playing animation over row image while playing (will get the gif from Milan)

### VIDEO
![IMG_0359](https://user-images.githubusercontent.com/2242281/224067696-ccde60de-ee08-4b03-a1ea-eedd372c928d.jpg)

- Download icon should be greyed out, not just hidden (otherwise it looks weird with that empty space)
- Let's remove the dot next to the date label (there is nothing next to it on the right side so it makes no sense). 

### DETAILS SCREEN
- Spaces between labels and dots should be always the same
- If episode is PLAYED, then on details view we should show "Mark as not played"
- If downloaded, then on details view we should show "Erase from memory" or something like that.
