### ISSUE TITLE
Implement recently played on Feed

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-ios#54]
Right now, if you play a podcast that is not part of a tribe, you have to search for the podcast again to get to it if you navigate away from playing that episode.

- Tap Feed
- Tap Listen
- Search for a podcast (Kevin Rooke Podcast)
- Play an episode
- Force quite and reopen, a new search is required to continue playing

Adding the 'recently played' section from the figma design will show episodes in reverse chronological order from when played.

**Comment by tomastiminskas** [comment]
@pitoi @jimBeaux27 we have the SUBSCRIBE button on the podcast player view, so if you tap on it after searching a podcast on the search, it will be persisted and it will start appearing on your feed. In addition it will store information about last episode played, current time, etc. 

@pitoi  do you think it worths it to implement recently played section considering this? Just asking because @jimBeaux27 ask to work on this. 

Also there is no design for RECENTLY PLAYED section on feed. We could add it on ALL tab since we have just 1 subsection there, but we are adding RECOMMENDATIONS there.

**Comment by tomastiminskas** [comment]
This is implemented already
