### ISSUE TITLE
Profiles: profile display in tribes - iOS App

### ISSUE THREAD

**Issue by soup20** [stakwork/sphinx-ios#67]
**Service involved:**
iOS app

**Goal:**
Create a display for a user's tribe-specific profile information, which is returned from the tribes-server when someone clicks on their username in a tribe.

**Method:**
- Profile information will be returned here: `tribes.sphinx.chat/person/uuid/{uuid}`
- It should be displayed according to Milan's design below:
![Image](https://user-images.githubusercontent.com/104323003/199917211-e92cacdb-98e4-4c26-b74b-66b000a49933.png)

*for getting the badge icons using the badge IDs: https://liquid.sphinx.chat/list

**Comment by tomastiminskas** [comment]
@soup20 here are some questions about this new feature:

- is `uuid` the uuid of the message where the user tap? 
- How is the json structure of the tribes server endpoint response? Having an example in this ticket will be helpful so we are all on the same page. 
- Will it work for old messages? Or just for messages sent since the feature has been deployed? 
- Is this already pushed to tribe server?

**Comment by tomastiminskas** [comment]
@soup20  regarding this:

**the uuid is for a person, not a message. So each person in the tribe has a uuid that is attached to all their messages.**

So now each message on tribes will have a new field representing the sender uuid? What is the name of this new field? Because messages already have `uuid` column for message uuid
