### ISSUE TITLE
Allow boost on recommendations

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-ios#86]

**Comment by jimBeaux27** [comment]
@tomastiminskas I took a look at this. The biggest problem here is that it seems the endpoints for recommendations do not actually give us the information we'd need to accomplish enabling boosts:
Recommendation Result:
![recommendation_results](https://user-images.githubusercontent.com/96802642/213878554-dd3a6de5-d8db-4f96-9925-add860bf6dc2.png)
Fully Processed Podcast Object:
![podcastResult](https://user-images.githubusercontent.com/96802642/213878980-7329cbfc-a682-4db3-9de1-860006713476.png)

To enable boosts, at a minimum we would need the feedID of the podcast so that we could do an additonal query to getPodcastInfo on the back end. Even better than that would be to include a destinationArray so that we could immediately plug that in for the boost.

**Comment by tomastiminskas** [comment]
@jimBeaux27 we actually don't need that. The recommendation object has a pub key which can be used as the destination. Then to create the boost message we just need the itemID, the currentTime and the amount (which will be the tip amount set by the user on Profile). So we have everything

Feel free to work on this since it's something we need to add. Just let me know if you have questions.
