### ISSUE TITLE
Artwork Bleeding Outside Boundaries for Podcasts

### ISSUE THREAD

**Issue by uncleJim21** [stakwork/sphinx-ios#97]

**Comment by jimBeaux27** [comment]
@pitoi this was something you reported on our phone call earlier this week. I have not yet seen this happen. Could you attach screenshots or provide guidance on how to recreate when you get a minute?

**Comment by pitoi** [comment]
![IMG_51B6137BD079-1](https://user-images.githubusercontent.com/814886/210188625-b8fcbb3d-0a21-4a77-b842-ee0fd8b65c35.jpeg)
![IMG_7D8B03092259-1](https://user-images.githubusercontent.com/814886/210188629-9cf53e63-fe3c-4a60-
![IMG_B51AC9165D05-1](https://user-images.githubusercontent.com/814886/210188652-448ef739-5e00-4f70-963b-46ccf2a85d4c.jpeg)
95ff-b29024f1e503.jpeg)

**Comment by jimBeaux27** [comment]
Ok @pitoi sounds like a simple case of just adjusting the zoom or scaling somehow thanks for sharing

**Comment by jimBeaux27** [comment]
@pitoi thanks Paul. I was able to recreate it by simulating it on a more oblong device vs my iPhone 7.

@tomastiminskas What's happening is we are altering the 1:1 ratio specified in the storyboard by adding the inset constant (due to the fact that it's page presentation). When that happens, it is no longer a 1:1 ratio hence the distortion. 

There are a lot of ways to attack this but it doesn't seem like any of them can be done without re-laying out the entire view & I just want to talk about how to go about it. What it really comes down to is that the height and width should both be the width of the screen but trying to do that would break other assumptions in the view.

**Comment by tomastiminskas** [comment]
@jimBeaux27 I will take care of this one
